apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: rabbit
      port: 25672
      targetPort: 25672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        ports:
          - containerPort: 5672
            name: amqp
          - containerPort: 15672
            name: http
          - containerPort: 4369
            name: epmd
          - containerPort: 25672
            name: rabbit
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-user
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-password
        volumeMounts:
          - name: persistent-volume
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: rabbitmq-dat

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: testrabbitmq
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/var/lib/rabbitmq"
  storageClassName: testrabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-dat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

