apiVersion: v1
kind: Secret
metadata:
  name: secret-db-postgres
  namespace: postgresql
type: Opaque
data:
  'script.sql': Q1JFQVRFIERBVEFCQVNFICJrb25nIjsKQ1JFQVRFIFVTRVIgImtvbmciIFdJVEggRU5DUllQVEVEIFBBU1NXT1JEICdrb25nMTIzJzsKR1JBTlQgQUxMIFBSSVZJTEVHRVMgT04gREFUQUJBU0UgImtvbmciIFRPICJrb25nIjsK
